//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.7
//
// <auto-generated>
//
// Generated from file `SmartHome.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SmartHome;

/** @hidden */
public class _LightBulbPrxI extends com.zeroc.Ice._ObjectPrxI implements LightBulbPrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
