//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.7
//
// <auto-generated>
//
// Generated from file `SmartHome.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SmartHome;

public class InvalidTime extends com.zeroc.Ice.UserException
{
    public InvalidTime()
    {
        this.time = new Time();
    }

    public InvalidTime(Throwable cause)
    {
        super(cause);
        this.time = new Time();
    }

    public InvalidTime(Time time)
    {
        this.time = time;
    }

    public InvalidTime(Time time, Throwable cause)
    {
        super(cause);
        this.time = time;
    }

    public String ice_id()
    {
        return "::SmartHome::InvalidTime";
    }

    public Time time;

    /** @hidden */
    @Override
    protected void _writeImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice("::SmartHome::InvalidTime", -1, true);
        Time.ice_write(ostr_, time);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _readImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        time = Time.ice_read(istr_);
        istr_.endSlice();
    }

    /** @hidden */
    public static final long serialVersionUID = -1691351637L;
}
