//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.7
//
// <auto-generated>
//
// Generated from file `SmartHome.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SmartHome;

public enum Modes implements java.io.Serializable
{
    ConventionalOvenCooking(0),
    FanForced(1),
    FanForcedGrill(2),
    Grill(3),
    TurboGrill(4),
    Defrost(5),
    Warmer(6),
    ECO(7),
    Pyrolytic(8),
    PizzaMode(9),
    FishCooking(10),
    BreadProving(11);

    public int value()
    {
        return _value;
    }

    public static Modes valueOf(int v)
    {
        switch(v)
        {
        case 0:
            return ConventionalOvenCooking;
        case 1:
            return FanForced;
        case 2:
            return FanForcedGrill;
        case 3:
            return Grill;
        case 4:
            return TurboGrill;
        case 5:
            return Defrost;
        case 6:
            return Warmer;
        case 7:
            return ECO;
        case 8:
            return Pyrolytic;
        case 9:
            return PizzaMode;
        case 10:
            return FishCooking;
        case 11:
            return BreadProving;
        }
        return null;
    }

    private Modes(int v)
    {
        _value = v;
    }

    public void ice_write(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeEnum(_value, 11);
    }

    public static void ice_write(com.zeroc.Ice.OutputStream ostr, Modes v)
    {
        if(v == null)
        {
            ostr.writeEnum(SmartHome.Modes.ConventionalOvenCooking.value(), 11);
        }
        else
        {
            ostr.writeEnum(v.value(), 11);
        }
    }

    public static Modes ice_read(com.zeroc.Ice.InputStream istr)
    {
        int v = istr.readEnum(11);
        return validate(v);
    }

    public static void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Modes> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    public static void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, Modes v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.Size))
        {
            ice_write(ostr, v);
        }
    }

    public static java.util.Optional<Modes> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.Size))
        {
            return java.util.Optional.of(ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static Modes validate(int v)
    {
        final Modes e = valueOf(v);
        if(e == null)
        {
            throw new com.zeroc.Ice.MarshalException("enumerator value " + v + " is out of range");
        }
        return e;
    }

    private final int _value;
}
