//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.7
//
// <auto-generated>
//
// Generated from file `SmartHome.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SmartHome;

public class UnsupportedMode extends com.zeroc.Ice.UserException
{
    public UnsupportedMode()
    {
        this.unsupportedMode = Modes.LOW;
    }

    public UnsupportedMode(Throwable cause)
    {
        super(cause);
        this.unsupportedMode = Modes.LOW;
    }

    public UnsupportedMode(Modes[] supportedModes, Modes unsupportedMode)
    {
        this.supportedModes = supportedModes;
        this.unsupportedMode = unsupportedMode;
    }

    public UnsupportedMode(Modes[] supportedModes, Modes unsupportedMode, Throwable cause)
    {
        super(cause);
        this.supportedModes = supportedModes;
        this.unsupportedMode = unsupportedMode;
    }

    public String ice_id()
    {
        return "::SmartHome::UnsupportedMode";
    }

    public Modes[] supportedModes;

    public Modes unsupportedMode;

    /** @hidden */
    @Override
    protected void _writeImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice("::SmartHome::UnsupportedMode", -1, true);
        ModesSequenceHelper.write(ostr_, supportedModes);
        Modes.ice_write(ostr_, unsupportedMode);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _readImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        supportedModes = ModesSequenceHelper.read(istr_);
        unsupportedMode = Modes.ice_read(istr_);
        istr_.endSlice();
    }

    /** @hidden */
    public static final long serialVersionUID = -1719050973L;
}
