package pl.edu.agh;

public enum Commands {
    TURN_ON, TURN_OFF, CHECK_POWER, GET_PHOTO_SIZE, SET_PHOTO_SIZE, GET_PHOTO, TURN_LIGHT_ON, TURN_LIGHT_OFF,
    IS_LIGHT_ON, GET_MIN_TEMPERATURE, GET_MAX_TEMPERATURE, GET_CURRENT_TEMPERATURE, SET_TEMPERATURE,
    GET_SUPPORTED_MODES, START, STOP, RESET, GET_TIME, SET_TIME, IS_FINISH, GET_HUMIDITY
}
